# Generated by Django 5.1.1 on 2024-09-26 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=50)),
                ('age', models.IntegerField()),
                ('description', models.TextField()),
                ('dob', models.DateField()),
            ],
        ),
    ]
